"""Initial migration - create all tables

Revision ID: 35c0afba121e
Revises: 
Create Date: 2025-11-30 13:21:07.904803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c0afba121e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False, comment="Domain name (e.g., 'amazon.com')"),
    sa.Column('base_url', sa.String(length=512), nullable=False, comment="Base URL (e.g., 'https://www.amazon.com')"),
    sa.Column('parser_name', sa.String(length=100), nullable=False, comment="Parser to use (e.g., 'amazon', 'ebay')"),
    sa.Column('crawl_delay_seconds', sa.Integer(), nullable=False, comment='Minimum delay between requests (seconds)'),
    sa.Column('max_concurrent_requests', sa.Integer(), nullable=False, comment='Maximum concurrent requests to this domain'),
    sa.Column('default_crawl_frequency', sa.Interval(), server_default='1 day', nullable=False, comment='Default recrawl frequency (PostgreSQL INTERVAL)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Enable/disable crawling for this domain'),
    sa.Column('robots_txt_url', sa.String(length=512), nullable=True, comment='robots.txt URL'),
    sa.Column('robots_txt_content', sa.Text(), nullable=True, comment='Cached robots.txt content'),
    sa.Column('robots_txt_last_fetched', sa.TIMESTAMP(timezone=True), nullable=True, comment='When robots.txt was last fetched'),
    sa.Column('user_agent', sa.String(length=255), nullable=False, comment='User agent string for this domain'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_domain_name'), 'domains', ['domain_name'], unique=True)
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_is_active'), 'domains', ['is_active'], unique=False)
    op.create_index(op.f('ix_domains_parser_name'), 'domains', ['parser_name'], unique=False)
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proxy_url', sa.String(length=255), nullable=False, comment='Proxy host/IP address'),
    sa.Column('proxy_port', sa.Integer(), nullable=False, comment='Proxy port number'),
    sa.Column('proxy_protocol', sa.String(length=20), nullable=False, comment='Protocol (http, https, socks5)'),
    sa.Column('proxy_username', sa.String(length=100), nullable=True, comment='Authentication username'),
    sa.Column('proxy_password', sa.String(length=255), nullable=True, comment='Authentication password (should be encrypted)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether proxy is active'),
    sa.Column('failure_count', sa.Integer(), nullable=False, comment='Consecutive failure count'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='Total successful requests'),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Last time proxy was used'),
    sa.Column('last_success_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Last successful request'),
    sa.Column('last_failure_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Last failed request'),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True, comment='Average response time in milliseconds'),
    sa.Column('country_code', sa.String(length=2), nullable=True, comment='Proxy country code (ISO 3166-1 alpha-2)'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='Proxy city'),
    sa.Column('provider', sa.String(length=100), nullable=True, comment='Proxy provider name'),
    sa.Column('monthly_cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='Monthly cost for cost tracking'),
    sa.Column('max_requests_per_hour', sa.Integer(), nullable=False, comment='Rate limit for this proxy'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxies_country_code'), 'proxies', ['country_code'], unique=False)
    op.create_index(op.f('ix_proxies_failure_count'), 'proxies', ['failure_count'], unique=False)
    op.create_index(op.f('ix_proxies_id'), 'proxies', ['id'], unique=False)
    op.create_index(op.f('ix_proxies_is_active'), 'proxies', ['is_active'], unique=False)
    op.create_index(op.f('ix_proxies_last_used_at'), 'proxies', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_proxies_provider'), 'proxies', ['provider'], unique=False)
    op.create_table('crawl_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False, comment='Reference to domain'),
    sa.Column('proxy_id', sa.Integer(), nullable=True, comment='Proxy used for this request'),
    sa.Column('url', sa.Text(), nullable=False, comment='Full URL to crawl'),
    sa.Column('url_hash', sa.String(length=64), nullable=False, comment='SHA256 hash of URL (deduplication)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Current task status'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Priority (1=highest, 10=lowest)'),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='When to execute task'),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='When crawling started'),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='When task completed/failed'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retry attempts (current phase)'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='Max retries before marking failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Last error message'),
    sa.Column('crawl_frequency', sa.Interval(), server_default='1 day', nullable=False, comment='How often to re-crawl (PostgreSQL INTERVAL)'),
    sa.Column('next_crawl_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Next scheduled crawl time'),
    sa.Column('recrawl_count', sa.Integer(), nullable=False, comment='Total number of times recrawled'),
    sa.Column('is_recurring', sa.Boolean(), nullable=False, comment='Whether to schedule next crawl'),
    sa.Column('html_path', sa.String(length=512), nullable=True, comment='Path to saved HTML file (local or S3)'),
    sa.Column('http_status_code', sa.Integer(), nullable=True, comment='HTTP response code (200, 404, 500, etc.)'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='Response time in milliseconds'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='First creation time'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='Who created task (system/admin/api)'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_tasks_created_by'), 'crawl_tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_domain_id'), 'crawl_tasks', ['domain_id'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_id'), 'crawl_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_is_recurring'), 'crawl_tasks', ['is_recurring'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_next_crawl_at'), 'crawl_tasks', ['next_crawl_at'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_priority'), 'crawl_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_proxy_id'), 'crawl_tasks', ['proxy_id'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_scheduled_at'), 'crawl_tasks', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_status'), 'crawl_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_url_hash'), 'crawl_tasks', ['url_hash'], unique=True)
    op.create_table('domain_proxies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False, comment='Reference to domain'),
    sa.Column('proxy_id', sa.Integer(), nullable=False, comment='Reference to proxy'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Enable/disable this mapping'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Proxy priority for this domain (1=highest, 10=lowest)'),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Last time this proxy was used for THIS domain'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='Successful requests for this domain'),
    sa.Column('failure_count', sa.Integer(), nullable=False, comment='Failed requests for this domain'),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True, comment='Average response time for this domain (milliseconds)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'proxy_id', name='unique_domain_proxy')
    )
    op.create_index('idx_domain_proxies_lru', 'domain_proxies', ['domain_id', 'last_used_at'], unique=False)
    op.create_index('idx_domain_proxies_priority_lru', 'domain_proxies', ['domain_id', 'priority', 'last_used_at'], unique=False)
    op.create_index(op.f('ix_domain_proxies_domain_id'), 'domain_proxies', ['domain_id'], unique=False)
    op.create_index(op.f('ix_domain_proxies_id'), 'domain_proxies', ['id'], unique=False)
    op.create_index(op.f('ix_domain_proxies_is_active'), 'domain_proxies', ['is_active'], unique=False)
    op.create_index(op.f('ix_domain_proxies_proxy_id'), 'domain_proxies', ['proxy_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False, comment='Source domain'),
    sa.Column('crawl_task_id', sa.Integer(), nullable=True, comment='Original crawl task that created this product'),
    sa.Column('url', sa.Text(), nullable=False, comment='Product page URL'),
    sa.Column('url_hash', sa.String(length=64), nullable=False, comment='SHA256 hash of URL (deduplication)'),
    sa.Column('product_name', sa.String(length=512), nullable=False, comment='Product name/title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Full product description (indexed in Elasticsearch)'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Current price'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency code (ISO 4217: USD, EUR, GBP)'),
    sa.Column('availability', sa.String(length=50), nullable=True, comment='Stock status (in_stock, out_of_stock, preorder, discontinued)'),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True, comment='Product rating (0.00-5.00)'),
    sa.Column('review_count', sa.Integer(), nullable=True, comment='Number of reviews'),
    sa.Column('brand', sa.String(length=255), nullable=True, comment='Brand name'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Product category'),
    sa.Column('sku', sa.String(length=100), nullable=True, comment='Stock keeping unit'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA256 hash of product data (detect changes)'),
    sa.Column('extra_attributes', sa.JSON(), nullable=True, comment='Additional metadata (color, size, weight, etc.)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='First crawled timestamp'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last updated timestamp'),
    sa.ForeignKeyConstraint(['crawl_task_id'], ['crawl_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_availability'), 'products', ['availability'], unique=False)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_crawl_task_id'), 'products', ['crawl_task_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_domain_id'), 'products', ['domain_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_index(op.f('ix_products_rating'), 'products', ['rating'], unique=False)
    op.create_index(op.f('ix_products_url_hash'), 'products', ['url_hash'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Reference to product'),
    sa.Column('image_url', sa.Text(), nullable=False, comment='Original image URL from source website'),
    sa.Column('image_path', sa.String(length=512), nullable=True, comment='Local/S3 storage path (NULL if not downloaded yet)'),
    sa.Column('alt_text', sa.String(length=512), nullable=True, comment='Image alt text/description'),
    sa.Column('image_type', sa.String(length=50), nullable=False, comment='Image type (primary, gallery, thumbnail)'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Display order (0=first, position for gallery carousel)'),
    sa.Column('width', sa.Integer(), nullable=True, comment='Image width in pixels'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Image height in pixels'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation time'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_image_type'), 'images', ['image_type'], unique=False)
    op.create_index(op.f('ix_images_product_id'), 'images', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_product_id'), table_name='images')
    op.drop_index(op.f('ix_images_image_type'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_products_url_hash'), table_name='products')
    op.drop_index(op.f('ix_products_rating'), table_name='products')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_domain_id'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_crawl_task_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_index(op.f('ix_products_availability'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_domain_proxies_proxy_id'), table_name='domain_proxies')
    op.drop_index(op.f('ix_domain_proxies_is_active'), table_name='domain_proxies')
    op.drop_index(op.f('ix_domain_proxies_id'), table_name='domain_proxies')
    op.drop_index(op.f('ix_domain_proxies_domain_id'), table_name='domain_proxies')
    op.drop_index('idx_domain_proxies_priority_lru', table_name='domain_proxies')
    op.drop_index('idx_domain_proxies_lru', table_name='domain_proxies')
    op.drop_table('domain_proxies')
    op.drop_index(op.f('ix_crawl_tasks_url_hash'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_status'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_scheduled_at'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_proxy_id'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_priority'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_next_crawl_at'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_is_recurring'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_id'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_domain_id'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_created_by'), table_name='crawl_tasks')
    op.drop_table('crawl_tasks')
    op.drop_index(op.f('ix_proxies_provider'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_last_used_at'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_is_active'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_id'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_failure_count'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_country_code'), table_name='proxies')
    op.drop_table('proxies')
    op.drop_index(op.f('ix_domains_parser_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_is_active'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_domain_name'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
